### ISSUE TITLE
NPM Package missing module type

### ISSUE THREAD

**Issue by neilcampbell** [Kount/kount-web-sdk#2]
Hi,
The current NPM package (1.1.6) published at https://www.npmjs.com/package/@kount/kount-web-client-sdk doesn't specify `"type": "module"` inside the package.json file and as a result node interprets this package as a commonjs module (the default) rather than an es module, which causes loading errors.

Are you able to please update the package.json to include `"type": "module"`.

**Comment by lassediercks** [comment]
is there any obvious quickfix for this that I can perform locally?

**Comment by neilcampbell** [comment]
The easiest way without an actual fix is to use the `patch-package` library inside your app to apply the follow patch.

```
diff --git a/node_modules/@kount/kount-web-client-sdk/package.json b/node_modules/@kount/kount-web-client-sdk/package.json
index 160904b..736a434 100644
--- a/node_modules/@kount/kount-web-client-sdk/package.json
+++ b/node_modules/@kount/kount-web-client-sdk/package.json
@@ -1,4 +1,5 @@
 {
+  "type": "module",
   "name": "@kount/kount-web-client-sdk",
   "version": "1.1.6",
   "description": "Kount's Web Client SDK. See https://github.com/Kount/kount-web-sdk/blob/master/README.md for more information.",
```

**Comment by lassediercks** [comment]
Thanks for the answer neil, meanwhile I found out my real problem is the package being in es6, not providing a cjs version. Last version I consumed was 1.13 
Code works but jest and es6 is really weird. Thanks again!

**Comment by gjd-keynetics** [comment]
Fixed in March 2024 release.
