### ISSUE TITLE
Checking window properties is missing typeof operator 

### ISSUE THREAD

**Issue by daniel-beet** [Kount/kount-web-sdk#6]
These are errors reported by a SonarQube scan of this code. The if condition is always true. This is probably not an issue for modern browsers, but could be for older clients.

https://github.com/Kount/kount-web-sdk/blob/cd0c50f4bad624ec88368d2f9895cea8117f69a5/kount-web-client-sdk.js#L671

`if (window.postMessage !== 'undefined' && window.onmessage !== 'undefined') {`

Errors:
Remove this "!==" check; it will always be true. Did you mean to use "!="?

It looks like these are attempting to check if the properties are undefined, so could be either:

`if (window.postMessage !== undefined && window.onmessage !== undefined) {`

or

`if (typeof window.postMessage !== 'undefined' && typeof window.onmessage !== 'undefined') {`

**Comment by gjd-keynetics** [comment]
Moved to Jira backlog.
